#!/usr/bin/env bash

# Get OISD list
curl https://big.oisd.nl/ -o ../oisd.txt

# Create compiled blocklist
time hostlist-compiler -v -c hostlist-compiler-config.json -o blocklist

# Remove all whitelisted entries
sed -i '/^@@/d' blocklist

# Remove empty lines
sed -i '/^$/d' blocklist

# (Optional) Remove rules that are too long
#sed -i '/^.\{1024\}./d' blocklist
