name: Automated Checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  pre-commit:
    name: pre-commit Checks
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          check-latest: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Hostlist Compiler
        run: npm install -g @adguard/hostlist-compiler

      - name: Run compile-hostlist script
        run: |
          chmod +x ./compile-hostlist
          ./compile-hostlist

      - name: Run Pre Commit Checks
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
        continue-on-error: true

      - name: Auto-commit blocklist and formatting changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Blocklist update $(date '+%Y-%m-%d') $(date '+%H:%M:%S')"
          file_pattern: "blocklist *.md"
